In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_validate,cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
df=pd.read_csv("heart_disease.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,57,1,0,119,182,0,1,153,1,1.0,2,2,2,1
1,44,1,2,123,170,0,0,171,0,0.3,2,0,3,0
2,61,0,0,138,211,0,0,147,0,0.2,1,0,3,1
3,63,1,3,105,277,0,0,143,0,0.5,0,0,3,1
4,35,1,0,98,122,0,0,176,0,2.2,2,1,3,0

In [ ]:
df.info

<bound method DataFrame.info of        age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0       57    1   0       119   182    0        1      153      1      1.0
1       44    1   2       123   170    0        0      171      0      0.3
2       61    0   0       138   211    0        0      147      0      0.2
3       63    1   3       105   277    0        0      143      0      0.5
4       35    1   0        98   122    0        0      176      0      2.2
...    ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
12229   47    0   2       120   120    0        0      182      0      0.6
12230   50    1   2       103   202    0        1      146      0      2.1
12231   63    1   2        91   198    1        0      128      0      0.4
12232   64    0   2       127   273    0        0      132      0      0.5
12233   45    1   2       140   227    0        1      167      0      3.8

       slope  ca  thal  target
0          2   2     2       1
1          2   0     3       0
2          1   0     3       1
3          0   0     3       1
4          2   1     3       0
...      ...  ..   ...     ...
12229      2   2     3       0
12230      1   0     2       0
12231      2   0     2       0
12232      2   0     2       0
12233      1   0     2       1

[12234 rows x 14 columns]>

In [ ]:
#find null values
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
#duplicat rows
df.duplicated().sum()

np.int64(0)

In [ ]:
#split the data
x = df.drop("target",axis=1)
y = df["target"]

In [ ]:
#splitting the datast for traing and testing
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
#model taring
print("Training Data shape:", x_train.shape)
print("Testing Data shape:", x_test.shape)

Training Data shape: (9787, 13)
Testing Data shape: (2447, 13)

In [ ]:

LR = LogisticRegression(max_iter=1000)
LR.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [ ]:
#testing accuracy
y_pred = LR.predict(x_test)
accuracy=accuracy_score(y_pred,y_test)
print("Testing Accuracy : ",accuracy)

Testing Accuracy :  0.8708622803432775

In [ ]:
#training accuracy
y_pred = LR.predict(x_train)
accuracy=accuracy_score(y_pred, y_train)
print("Training Accuracy : ", accuracy)

Training Accuracy :  0.8710534382343925

In [ ]:
#validatin accuracy
val_accuracy = cross_val_score(
    LR,x_train,y_train,cv=5)
print("validation accuracy:",val_accuracy.mean())

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

validation accuracy: 0.871257991662417

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
#randomforest clasifer
RF=RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    min_samples_leaf=10,
    verbose=1,
    n_jobs=1

)

In [ ]:
RF.fit(x_train,y_train)

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.5s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.9s finished

RandomForestClassifier(max_depth=10, min_samples_leaf=10, n_jobs=1, verbose=1)

In [ ]:
#testing accuracy
y_pred_rf = RF.predict(x_test)
accuracy_rf=accuracy_score(y_pred_rf,y_test)
print("Testing Accuracy : ",accuracy)

Testing Accuracy :  0.8710534382343925

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished

In [23]:
#training accuracy
y_pred_rf = RF.predict(x_train)
accuracy_rf = accuracy_score(y_pred_rf, y_train)
print("Training Accuracy : ", accuracy)

Training Accuracy :  0.8710534382343925

In [24]:
#GradientBoostingClassifier
gb=GradientBoostingClassifier(
    n_estimators=100,
    min_samples_leaf=10,
    max_depth=10,
    learning_rate=0.1,
    random_state=42
)
gb.fit(x_train,y_train)

GradientBoostingClassifier(max_depth=10, min_samples_leaf=10, random_state=42)

In [26]:
#testing accuracy of GradientBoostingClassifie
y_pred_gb = gb.predict(x_test)
accuracy_gb=accuracy_score(y_pred_gb,y_test)
print("Testing Accuracy : ",accuracy)

Testing Accuracy :  0.8710534382343925

In [27]:
#training accuracy of GradientBoostingClassifie
y_pred_gb = gb.predict(x_train)
accuracy_gb = accuracy_score(y_pred_gb, y_train)
print("Training Accuracy : ", accuracy)

Training Accuracy :  0.8710534382343925

In [28]:
valid_gb = cross_val_score(gb,x_train,y_train,cv=5)
print("validation accuracy:",valid_gb.mean())

validation accuracy: 0.9088579119089015

In [36]:
# Calculate predictions on the test dataset to match the size of y_test
y_pred_gb_test = gb.predict(x_test)

# Calculate confusion matrix using (y_true, y_pred) order
confusion_matrix(y_test, y_pred_gb_test)

array([[1103,  103],
       [ 112, 1129]])

In [30]:
pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (3.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost) (1.16.3)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.32.3)

In [31]:
#xgboost Algorithm
from xgboost import XGBClassifier
xgb= XGBClassifier(
    n_estimators=20,
    max_depth=10,
    learning_rate=0.1,
    random_state=42
)
xgb.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=20,
              n_jobs=None, num_parallel_tree=None, ...)

In [32]:
#testing accuracy of XGBClassifier
y_pred_xgb = xgb.predict(x_test)
accuracy_xgb=accuracy_score(y_pred_xgb,y_test)
print("Testing Accuracy : ",accuracy)

Testing Accuracy :  0.8710534382343925

In [33]:
#training accuracy of XGBClassifier
y_pred_xgb = xgb.predict(x_train)
accuracy_xgb = accuracy_score(y_pred_xgb, y_train)
print("Training Accuracy : ", accuracy)

Training Accuracy :  0.8710534382343925

In [39]:
import joblib
joblib.dump({"model": gb, "features": list(x.columns)}, "heart.joblib", compress=3)

['heart.joblib']